<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('states')->insert([
            ['country_id' => 1, 'name' => 'Badakhshan'],
            ['country_id' => 1, 'name' => 'Badghis'],
            ['country_id' => 1, 'name' => 'Baghlan'],
            ['country_id' => 1, 'name' => 'Balkh'],
            ['country_id' => 1, 'name' => 'Bamyan'],
            ['country_id' => 1, 'name' => 'Daykundi'],
            ['country_id' => 1, 'name' => 'Farah'],
            ['country_id' => 1, 'name' => 'Faryab'],
            ['country_id' => 1, 'name' => 'Ghazni'],
            ['country_id' => 1, 'name' => 'Ghor'],
            ['country_id' => 1, 'name' => 'Helmand'],
            ['country_id' => 1, 'name' => 'Herat'],
            ['country_id' => 1, 'name' => 'Jowzjan'],
            ['country_id' => 1, 'name' => 'Kabul'],
            ['country_id' => 1, 'name' => 'Kandahar'],
            ['country_id' => 1, 'name' => 'Kapisa'],
            ['country_id' => 1, 'name' => 'Khost'],
            ['country_id' => 1, 'name' => 'Kunar'],
            ['country_id' => 1, 'name' => 'Kunduz'],
            ['country_id' => 1, 'name' => 'Laghman'],
            ['country_id' => 1, 'name' => 'Logar'],
            ['country_id' => 1, 'name' => 'Nangarhar'],
            ['country_id' => 1, 'name' => 'Nimroz'],
            ['country_id' => 1, 'name' => 'Nuristan'],
            ['country_id' => 1, 'name' => 'Paktia'],
            ['country_id' => 1, 'name' => 'Paktika'],
            ['country_id' => 1, 'name' => 'Panjshir'],
            ['country_id' => 1, 'name' => 'Parwan'],
            ['country_id' => 1, 'name' => 'Samangan'],
            ['country_id' => 1, 'name' => 'Sar-e Pol'],
            ['country_id' => 1, 'name' => 'Takhar'],
            ['country_id' => 1, 'name' => 'Urozgan'],
            ['country_id' => 1, 'name' => 'Wardak'],
            ['country_id' => 1, 'name' => 'Zabul'],
            ['country_id' => 2, 'name' => 'Berat'],
            ['country_id' => 2, 'name' => 'Dibër'],
            ['country_id' => 2, 'name' => 'Durrës'],
            ['country_id' => 2, 'name' => 'Elbasan'],
            ['country_id' => 2, 'name' => 'Fier'],
            ['country_id' => 2, 'name' => 'Gjirokastër'],
            ['country_id' => 2, 'name' => 'Korçë'],
            ['country_id' => 2, 'name' => 'Kukës'],
            ['country_id' => 2, 'name' => 'Lezhë'],
            ['country_id' => 2, 'name' => 'Shkodër'],
            ['country_id' => 2, 'name' => 'Tirana'],
            ['country_id' => 2, 'name' => 'Vlorë'],
            ['country_id' => 3, 'name' => 'Adrar'],
            ['country_id' => 3, 'name' => 'Chlef'],
            ['country_id' => 3, 'name' => 'Laghouat'],
            ['country_id' => 3, 'name' => 'Oum El Bouaghi'],
            ['country_id' => 3, 'name' => 'Batna'],
            ['country_id' => 3, 'name' => 'Béjaïa'],
            ['country_id' => 3, 'name' => 'Biskra'],
            ['country_id' => 3, 'name' => 'Bordj Bou Arréridj'],
            ['country_id' => 3, 'name' => 'Bouira'],
            ['country_id' => 3, 'name' => 'Tamanghasset'],
            ['country_id' => 3, 'name' => 'Tébessa'],
            ['country_id' => 3, 'name' => 'Tlemcen'],
            ['country_id' => 3, 'name' => 'Tiaret'],
            ['country_id' => 3, 'name' => 'Tizi Ouzou'],
            ['country_id' => 3, 'name' => 'Algiers'],
            ['country_id' => 3, 'name' => 'Djelfa'],
            ['country_id' => 3, 'name' => 'Jijel'],
            ['country_id' => 3, 'name' => 'Sétif'],
            ['country_id' => 3, 'name' => 'Saïda'],
            ['country_id' => 3, 'name' => 'Skikda'],
            ['country_id' => 3, 'name' => 'Sidi Bel Abbès'],
            ['country_id' => 3, 'name' => 'Annaba'],
            ['country_id' => 3, 'name' => 'Guelma'],
            ['country_id' => 3, 'name' => 'Constantine'],
            ['country_id' => 3, 'name' => 'Médéa'],
            ['country_id' => 3, 'name' => 'Mostaganem'],
            ['country_id' => 3, 'name' => 'M’Sila'],
            ['country_id' => 3, 'name' => 'Mascara'],
            ['country_id' => 3, 'name' => 'Oued El Harrach'],
            ['country_id' => 3, 'name' => 'El Oued'],
            ['country_id' => 3, 'name' => 'Khenchela'],
            ['country_id' => 3, 'name' => 'Souk Ahras'],
            ['country_id' => 3, 'name' => 'Tipasa'],
            ['country_id' => 3, 'name' => 'Mila'],
            ['country_id' => 3, 'name' => 'Aïn Témouchent'],
            ['country_id' => 3, 'name' => 'Naama'],
            ['country_id' => 3, 'name' => 'Aïn Defla'],
            ['country_id' => 3, 'name' => 'Tindouf'],
            ['country_id' => 3, 'name' => 'Tissemsilt'],
            ['country_id' => 3, 'name' => 'El Bayadh'],
            ['country_id' => 3, 'name' => 'Illizi'],
            ['country_id' => 3, 'name' => 'Bordj Badji Mokhtar'],
            ['country_id' => 3, 'name' => 'Ouargla'],
            ['country_id' => 3, 'name' => 'El M’ghair'],
            ['country_id' => 3, 'name' => 'El Menia'],
            ['country_id' => 3, 'name' => 'Ghardaïa'],
            ['country_id' => 3, 'name' => 'El Naama'],
            ['country_id' => 3, 'name' => 'El Tarf'],
            ['country_id' => 3, 'name' => 'El Oued'],
            ['country_id' => 4, 'name' => 'Tutuila'],
            ['country_id' => 4, 'name' => 'Manu\'a'],
            ['country_id' => 4, 'name' => 'Aunu\'u'],
            ['country_id' => 4, 'name' => 'Swains Island'],
            ['country_id' => 101, 'name' => 'Andhra Pradesh'],
            ['country_id' => 101, 'name' => 'Arunachal Pradesh'],
            ['country_id' => 101, 'name' => 'Assam'],
            ['country_id' => 101, 'name' => 'Bihar'],
            ['country_id' => 101, 'name' => 'Chhattisgarh'],
            ['country_id' => 101, 'name' => 'Goa'],
            ['country_id' => 101, 'name' => 'Gujarat'],
            ['country_id' => 101, 'name' => 'Haryana'],
            ['country_id' => 101, 'name' => 'Himachal Pradesh'],
            ['country_id' => 101, 'name' => 'Jharkhand'],
            ['country_id' => 101, 'name' => 'Karnataka'],
            ['country_id' => 101, 'name' => 'Kerala'],
            ['country_id' => 101, 'name' => 'Madhya Pradesh'],
            ['country_id' => 101, 'name' => 'Maharashtra'],
            ['country_id' => 101, 'name' => 'Manipur'],
            ['country_id' => 101, 'name' => 'Meghalaya'],
            ['country_id' => 101, 'name' => 'Mizoram'],
            ['country_id' => 101, 'name' => 'Nagaland'],
            ['country_id' => 101, 'name' => 'Odisha'],
            ['country_id' => 101, 'name' => 'Punjab'],
            ['country_id' => 101, 'name' => 'Rajasthan'],
            ['country_id' => 101, 'name' => 'Sikkim'],
            ['country_id' => 101, 'name' => 'Tamil Nadu'],
            ['country_id' => 101, 'name' => 'Telangana'],
            ['country_id' => 101, 'name' => 'Tripura'],
            ['country_id' => 101, 'name' => 'Uttar Pradesh'],
            ['country_id' => 101, 'name' => 'Uttarakhand'],
            ['country_id' => 101, 'name' => 'West Bengal'],
            // Union Territories
            ['country_id' => 101, 'name' => 'Andaman and Nicobar Islands'],
            ['country_id' => 101, 'name' => 'Chandigarh'],
            ['country_id' => 101, 'name' => 'Dadra and Nagar Haveli and Daman and Diu'],
            ['country_id' => 101, 'name' => 'Lakshadweep'],
            ['country_id' => 101, 'name' => 'Delhi'],
            ['country_id' => 101, 'name' => 'Puducherry'],
            ['country_id' => 101, 'name' => 'Ladakh'],
            ['country_id' => 101, 'name' => 'Jammu and Kashmir'],
        ]);
    }
}
